# This file contains values from Cookiecutter

default_context:
  project_name: "ascii_parser"
  project_description: "Awesome `ascii_parser` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "ascii_parser"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.7
  github_name: "ascii_parser"
  email: "nathanesau1@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
